In [77]:
import math

import numpy as np
from sklearn.datasets import make_spd_matrix

In [5]:
np.random.seed(0)
rng = np.random.default_rng(seed=0)
n = 3
lambda_ = 5
sigma = 0.3

xbar = np.repeat(0.2, n)

C = make_spd_matrix(n)
Dsq, B = np.linalg.eigh(C)
D = np.sqrt(Dsq)

print('xbar:\n', xbar)
print('C:\n', C)
print('D:\n', D)
print('B:\n', B)

xbar:
 [0.2 0.2 0.2]
C:
 [[ 0.74441055 -0.50552535 -0.08513618]
 [-0.50552535  3.48581245  0.05719362]
 [-0.08513618  0.05719362  0.47383848]]
D:
 [0.66788556 0.82479747 1.89148077]
B:
 [[ 0.33258747  0.92645224 -0.176272  ]
 [ 0.037581    0.17374413  0.9840735 ]
 [ 0.94232332 -0.33391499  0.02296812]]


In [3]:
zs = np.random.standard_normal(size=(lambda_, n))
print('zs:\n', zs)

zs:
 [[ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574 -2.55298982]
 [ 0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852]]


In [4]:
BD = B * D  # B * D = B @ diag(D)
#xs = xbar + sigma * (zs @ BD.T)
xs = xbar + sigma * (zs @ BD.T)
print('xs:\n', xs)

xs:
 [[ 0.23421052  0.45881777  0.33942264]
 [ 0.58526026  0.1521829   0.13688064]
 [ 0.28043071 -1.25996809  0.29640516]
 [ 0.51595518 -0.17234523  0.24231361]
 [ 0.01327774  0.18011819  0.74931206]]


In [5]:
# Transformation to obtain zs:
#
#       x                       = m + sig * BDz
#   <=> (x-m) / sig             = BDz
#   <=> D^-1 B^-1 ((x-m) / sig) = z
#   <=> D^-1 B' ((x-m) / sig)   = z

for i, x in enumerate(xs):
    y = (x - xbar) / sigma
    #BD_inv = np.linalg.inv(np.diag(D)) @ B.T
    BD_inv = np.diag(1. / D) @ B.T
    z = BD_inv @ y
    print('z_{}:\n'.format(i), z)

z_0:
 [0.76103773 0.12167502 0.44386323]
z_1:
 [ 0.33367433  1.49407907 -0.20515826]
z_2:
 [ 0.3130677  -0.85409574 -2.55298982]
z_3:
 [ 0.6536186   0.8644362  -0.74216502]
z_4:
 [ 2.26975462 -1.45436567  0.04575852]


In [6]:
# Now in vectorized fashion:
ys = (xs - xbar) / sigma
BD_inv = np.diag(1. / D) @ B.T
zsb = ys @ BD_inv.T
print('zsb:\n', zsb)

zsb:
 [[ 0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574 -2.55298982]
 [ 0.6536186   0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567  0.04575852]]


# Like in the paper

In [91]:
n = 3
lambda_ = 7
rng = np.random.default_rng(0)
sigma = 0.3

xbar = np.repeat(0.2, n).reshape(n, 1)

C = make_spd_matrix(n)
D_sq, B = np.linalg.eigh(C)
D = np.diag(np.sqrt(D_sq))

z = rng.standard_normal(size=(n, lambda_))

BD = B @ D

x = xbar + sigma * (BD @ z)

y = (x - xbar) / sigma
assert np.allclose(y, BD @ z)

BD_inv = np.diag(1. / np.diag(D)) @ B.T

zb = BD_inv @ y
assert np.allclose(z, zb)
assert np.allclose(y, BD @ zb)