In [1]:
import os
import sys
sys.path.append(os.path.abspath('../../'))

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np

from anguilla.dominance import fast_non_dominated_sort, naive_non_dominated_sort

In [4]:
rng = np.random.default_rng(0)

In [5]:
def test(rng, size, target_n=None):
    ps = rng.uniform(size=size)
    ranks1 = fast_non_dominated_sort(ps, target_n=target_n)
    ranks2 = naive_non_dominated_sort(ps)
    assert np.all(ranks1 == ranks2)
    return ps, ranks1

def test_ps(ps, target_n=None):
    ranks = fast_non_dominated_sort(ps, target_n=target_n)
    return ps, ranks

In [6]:
test(rng, (3, 2))

(array([[0.63696169, 0.26978671],
        [0.04097352, 0.01652764],
        [0.81327024, 0.91275558]]),
 array([2, 1, 3]))

In [7]:
test(rng, (3, 2))

(array([[0.60663578, 0.72949656],
        [0.54362499, 0.93507242],
        [0.81585355, 0.0027385 ]]),
 array([1, 1, 1]))

In [8]:
ps, ranks = test(rng, (5, 2))
ps, ranks

(array([[0.85740428, 0.03358558],
        [0.72965545, 0.17565562],
        [0.86317892, 0.54146122],
        [0.29971189, 0.42268722],
        [0.02831967, 0.12428328]]),
 array([1, 2, 3, 2, 1]))

In [9]:
_, ranks = test_ps(ps, 2)
ranks

array([1, 0, 0, 0, 1])

In [10]:
ps = rng.uniform(size=(2, 2))
%timeit fast_non_dominated_sort(ps)

84.2 µs ± 2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
ps = rng.uniform(size=(100, 2))
%timeit fast_non_dominated_sort(ps)

1.51 ms ± 5.18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
%timeit fast_non_dominated_sort(ps, target_n=50)

1.22 ms ± 6.38 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [13]:
ps = rng.uniform(size=(100, 4))
%timeit fast_non_dominated_sort(ps)

1.21 ms ± 7.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit fast_non_dominated_sort(ps, target_n=50)

1.1 ms ± 5.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
ps = rng.uniform(size=(100, 10))
%timeit fast_non_dominated_sort(ps)

1.24 ms ± 8.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
%timeit fast_non_dominated_sort(ps, target_n=50)

1.17 ms ± 4.03 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
ps = rng.uniform(size=(100, 100))
%timeit fast_non_dominated_sort(ps)

3.22 ms ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit fast_non_dominated_sort(ps, target_n=50)

3.2 ms ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
ps = rng.uniform(size=(100, 1000))
%timeit fast_non_dominated_sort(ps)

15.8 ms ± 845 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%timeit fast_non_dominated_sort(ps, target_n=50)

15.2 ms ± 51.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
ps = rng.uniform(size=(1000, 4))
%timeit fast_non_dominated_sort(ps)

37.8 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%timeit fast_non_dominated_sort(ps, target_n=500)

36.7 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
ps = rng.uniform(size=(1000, 100))
%timeit fast_non_dominated_sort(ps)

240 ms ± 2.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%timeit fast_non_dominated_sort(ps, target_n=500)

234 ms ± 919 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
ps = rng.uniform(size=(1000, 1000))
%timeit fast_non_dominated_sort(ps)

1.57 s ± 21.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [26]:
%timeit fast_non_dominated_sort(ps, target_n=500)

1.56 s ± 18.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%timeit fast_non_dominated_sort(ps, target_n=200)

1.56 s ± 28.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
