In [55]:
import os
import sys
sys.path.append(os.path.abspath('../../'))

In [56]:
import numpy as np
import anguilla.hypervolume as hv

from anguilla.dominance import fast_non_dominated_sort

In [125]:
def rank(fitness_values):
        population_size = len(fitness_values)
        n_parents = 10
        ref_point = np.max(fitness_values[:n_parents], axis=0) + 1.0
        contrib = hv.contributions(fitness_values, ref_point)
        fronts = np.zeros(population_size, dtype=int)
        fast_non_dominated_sort(fitness_values, out=fronts)
        ranking_idx = np.argsort(fronts)
        last_rank = 1
        selected_individuals: List[int] = []
        last_front_individuals: List[int] = []
        k = 0
        while k < population_size:
            individual = ranking_idx[k]
            if fronts[individual] > last_rank:
                if k < n_parents:
                    last_rank += 1
                    selected_individuals += last_front_individuals
                    last_front_individuals = [individual]
                else:
                    break
            else:
                last_front_individuals.append(individual)
            k += 1
        selected_individuals = np.array(selected_individuals, dtype=int)
        last_front_individuals = np.array(last_front_individuals, dtype=int)
        # Select best using HV indicator
        remaining = n_parents - len(selected_individuals)
        if remaining > 0:
            last_front_contrib = contrib[last_front_individuals]
            tmp_idx = np.argsort(-last_front_contrib)
            tmp_idx = tmp_idx[:remaining]
            selected_individuals = np.concatenate([selected_individuals,
                                                   last_front_individuals[tmp_idx]], dtype=int)
        return selected_individuals

In [142]:
xs = np.random.default_rng().uniform(size=(30, 3))
print(xs)
rank(xs)

[[0.04971002 0.25956966 0.52786128]
 [0.65839716 0.8994224  0.57042234]
 [0.20422348 0.40745695 0.42366698]
 [0.62713478 0.04315244 0.64992065]
 [0.61041298 0.62710931 0.28541079]
 [0.3680862  0.05470941 0.20835542]
 [0.91897839 0.6009968  0.2748785 ]
 [0.70629644 0.14811012 0.09505836]
 [0.64553598 0.76802    0.19044925]
 [0.78707968 0.00282225 0.38249261]
 [0.00609302 0.19624744 0.40992622]
 [0.66945053 0.34341635 0.71292303]
 [0.15389157 0.28830047 0.72198954]
 [0.54970468 0.61713498 0.44390845]
 [0.62977097 0.98383036 0.20464176]
 [0.20432326 0.73884245 0.07880491]
 [0.95483012 0.02599562 0.5052506 ]
 [0.78362267 0.93612048 0.48561225]
 [0.95416507 0.69339158 0.258661  ]
 [0.4129452  0.20282797 0.68385515]
 [0.76389352 0.95014305 0.05946527]
 [0.28904165 0.9797385  0.34713371]
 [0.34524075 0.79967048 0.99177903]
 [0.88999544 0.41328192 0.50957201]
 [0.32056258 0.87629189 0.61891068]
 [0.80775815 0.98243558 0.25574373]
 [0.89716837 0.94767645 0.32163001]
 [0.57822398 0.98865945 0.84

array([29, 20,  3,  5,  7,  9, 10, 15, 21, 19])