In [1]:
import math
import time
import timeit
import numpy as np
import anguilla.hypervolume as hv

In [2]:
ref_p_3d = np.array([1.1, 1.1, 1.1], dtype=float)

ps_3d = np.array(
    [
        [6.56039859404455e-2, 0.4474014917277, 0.891923776019316],
        [3.74945443950542e-2, 3.1364039802686e-2, 0.998804513479922],
        [0.271275894554688, 0.962356894778677, 1.66911984440026e-2],
        [0.237023460537611, 0.468951509833942, 0.850825693417425],
        [8.35813910785332e-2, 0.199763306732937, 0.97627289850149],
        [1.99072649788403e-2, 0.433909411793732, 0.900736544810901],
        [9.60698311356187e-2, 0.977187045721721, 0.18940978121319],
        [2.68052822856208e-2, 2.30651870780559e-2, 0.999374541394087],
        [0.356223209018184, 0.309633114503212, 0.881607826507812],
        [0.127964409429531, 0.73123479272024, 0.670015513129912],
        [0.695473366395562, 0.588939459338073, 0.411663831140169],
        [0.930735605917613, 0.11813654121718, 0.346085234453039],
        [0.774030940645471, 2.83363630460836e-2, 0.632513362272141],
        [0.882561783965009, 4.80931050853475e-3, 0.470171849451808],
        [4.92340623346446e-3, 0.493836329534438, 0.869540936185878],
        [0.305054163869799, 0.219367569077876, 0.926725324323535],
        [0.575227233936948, 0.395585597387712, 0.715978815661927],
        [0.914091673974525, 0.168988399705031, 0.368618138912863],
        [0.225088318852838, 0.796785147906617, 0.560775067911755],
        [0.306941172015014, 0.203530333828304, 0.929710987422322],
        [0.185344081015371, 0.590388202293731, 0.785550343533082],
        [0.177181921358634, 0.67105558509432, 0.719924279669315],
        [0.668494587335475, 0.22012845825454, 0.710393164782469],
        [0.768639363955671, 0.256541291890516, 0.585986427942633],
        [0.403457020846225, 0.744309886218013, 0.532189088208334],
        [0.659545359568811, 0.641205442223306, 0.39224418355721],
        [0.156141960251846, 8.36191498217669e-2, 0.984188765446851],
        [0.246039496399399, 0.954377757574506, 0.16919711007753],
        [3.02243260456876e-2, 0.43842801306405, 0.898257962656493],
        [0.243139979715573, 0.104253945099703, 0.96437236853565],
        [0.343877707314699, 0.539556201272222, 0.768522757034998],
        [0.715293885551218, 0.689330705208567, 0.114794756629825],
        [1.27610149409238e-2, 9.47996983636579e-2, 0.995414573777096],
        [0.30565381275615, 0.792827267212719, 0.527257689476066],
        [0.43864576057661, 3.10389339442242e-2, 0.8981238674636],
    ]
)

In [3]:
hv.shark_contributions(ps_3d, ref_p_3d)

array([6.66900683e-05, 1.27052063e-05, 1.45153473e-02, 6.80707501e-04,
       4.86460918e-04, 1.59635724e-04, 9.35237153e-03, 7.38816827e-04,
       9.73449354e-04, 3.73033034e-03, 2.27674976e-03, 3.05265939e-03,
       5.86625018e-03, 8.33617977e-03, 3.61509047e-03, 6.90217889e-05,
       2.67173642e-03, 7.66193810e-04, 1.43917818e-03, 7.22979757e-05,
       9.12794195e-04, 1.37620025e-03, 3.30936198e-03, 1.90143581e-03,
       1.71245687e-03, 2.49798368e-03, 1.69423751e-04, 1.50575051e-03,
       1.13226411e-05, 5.48890368e-04, 1.28565415e-03, 2.62821322e-02,
       6.36034460e-04, 7.75883941e-04, 5.34042831e-03])

In [4]:
hv.contributions(ps_3d, ref_p_3d)

array([6.66900683e-05, 1.27052063e-05, 1.45153473e-02, 6.80707501e-04,
       4.86460918e-04, 1.59635724e-04, 9.35237153e-03, 7.38816827e-04,
       9.73449354e-04, 3.73033034e-03, 2.27674976e-03, 3.05265939e-03,
       5.86625018e-03, 8.33617977e-03, 3.61509047e-03, 6.90217889e-05,
       2.67173642e-03, 7.66193810e-04, 1.43917818e-03, 7.22979757e-05,
       9.12794195e-04, 1.37620025e-03, 3.30936198e-03, 1.90143581e-03,
       1.71245687e-03, 2.49798368e-03, 1.69423751e-04, 1.50575051e-03,
       1.13226411e-05, 5.48890368e-04, 1.28565415e-03, 2.62821322e-02,
       6.36034460e-04, 7.75883941e-04, 5.34042831e-03])

In [5]:
%timeit hv.calculate(ps_3d, ref_p_3d, ds='btree')

12.9 µs ± 464 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%timeit hv.calculate(ps_3d, ref_p_3d, ds='rbtree')

13.3 µs ± 209 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
%timeit hv.shark_calculate(ps_3d, ref_p_3d)

23.7 µs ± 3.95 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
%timeit hv.contributions(ps_3d, ref_p_3d, ds='btree')

22.6 µs ± 2.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%timeit hv.contributions(ps_3d, ref_p_3d, ds='rbtree')

22.1 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%timeit hv.shark_contributions(ps_3d, ref_p_3d)

27.5 µs ± 2.93 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%timeit hv.contributions_naive(ps_3d, ref_p_3d)

853 µs ± 27.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
def cliff_3d(n, rng=np.random.default_rng()):
    """Generate n Cliff3D points."""
    vs = rng.standard_normal(size=(n, 2))
    ys = np.zeros((n, 3))
    for i in range(n):
        c = np.linalg.norm(vs[i])
        ys[i, 0:2] = 10.0 * np.abs(vs[i]) / c
    ys[:, 2] = rng.uniform(low=0.0, high=10.0, size=n)
    return ys

In [13]:
def run_benchmark(ds='btree', nfronts=100, nruns=30):
    elapsed_shark = 0.0
    elapsed_anguilla = 0.0
    elapsed_anguilla_rbtree = 0.0

    front_sizes = np.arange(100, 1100, 100)
    
    shark_results = []
    anguilla_results = []
    anguilla_rbtree_results = []
    
    for front_size in front_sizes:
        
        print("-- FRONT SIZE ({}) --".format(front_size))
    
        for _ in range(100):
            ys = cliff_3d(front_size)
            ref_y = np.max(ys, axis=0) + 1e-4

            t_start = time.perf_counter_ns()
            for _ in range(nruns):
                vol2 = hv.shark_calculate(ys, ref_y)
            t_end = time.perf_counter_ns()
            t_diff = t_end - t_start
            elapsed_shark += t_diff / float(nruns)

            t_start = time.perf_counter_ns()
            for _ in range(nruns):
                vol1 = hv.calculate(ys, ref_y, ds=ds)
            t_end = time.perf_counter_ns()
            t_diff = t_end - t_start
            elapsed_anguilla += t_diff / float(nruns)

            assert math.isclose(vol2, vol1)

        elapsed_shark /= 100.0
        elapsed_anguilla /= 100.0
        shark_results.append(elapsed_shark)
        anguilla_results.append(elapsed_anguilla)

        print("HYPERVOLUME CALCULATION")
        print("Shark bindings: ", elapsed_shark, "ns")
        print("Anguilla: ", elapsed_anguilla, "ns")
        print("Speedup: ", elapsed_shark / elapsed_anguilla)

        elapsed_shark = 0.0
        elapsed_anguilla = 0.0

        for _ in range(100):
            ys = cliff_3d(front_size)
            ref_y = np.max(ys, axis=0) + 1e-4

            t_start = time.perf_counter_ns()
            for _ in range(nruns):
                contribs2 = hv.shark_contributions(ys, ref_y)
            t_end = time.perf_counter_ns()
            t_diff = t_end - t_start
            elapsed_shark += t_diff / float(nruns)

            t_start = time.perf_counter_ns()
            for _ in range(nruns):
                contribs1 = hv.contributions(ys, ref_y, ds=ds)
            t_end = time.perf_counter_ns()
            t_diff = t_end - t_start
            elapsed_anguilla += t_diff / float(nruns)

            assert np.allclose(contribs2, contribs1)

        elapsed_shark /= 100.0
        elapsed_anguilla /= 100.0
        shark_results.append(elapsed_shark)
        anguilla_results.append(elapsed_anguilla)

        print("HYPERVOLUME CONTRIBUTIONS")
        print("Shark bindings: ", elapsed_shark, "ns")
        print("Anguilla: ", elapsed_anguilla, "ns")
        print("Speedup: ", elapsed_shark / elapsed_anguilla)
        print("")

In [33]:
run_benchmark(ds='btree')

-- FRONT SIZE (100) --
HYPERVOLUME CALCULATION
Shark bindings:  74338.36666666668 ns
Anguilla:  42064.76666666666 ns
Speedup:  1.7672359211152966
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  109480.53333333334 ns
Anguilla:  78424.93333333335 ns
Speedup:  1.3959914108948344

-- FRONT SIZE (200) --
HYPERVOLUME CALCULATION
Shark bindings:  158640.30533333338 ns
Anguilla:  83321.08266666668 ns
Speedup:  1.9039635618753044
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  200751.70000000007 ns
Anguilla:  156458.7999999999 ns
Speedup:  1.283096252815439

-- FRONT SIZE (300) --
HYPERVOLUME CALCULATION
Shark bindings:  244467.6503333334 ns
Anguilla:  130638.75466666667 ns
Speedup:  1.871325633477666
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  313668.4333333334 ns
Anguilla:  257628.9333333334 ns
Speedup:  1.2175202112392138

-- FRONT SIZE (400) --
HYPERVOLUME CALCULATION
Shark bindings:  323460.31766666664 ns
Anguilla:  187412.38933333338 ns
Speedup:  1.7259281460381852
HYPERVOLUME CONTRIBUTIONS
Shark bi

In [15]:
run_benchmark(ds='rbtree')

-- FRONT SIZE (100) --
HYPERVOLUME CALCULATION
Shark bindings:  72131.8 ns
Anguilla:  48018.16666666666 ns
Speedup:  1.5021773009520707
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  103547.69999999994 ns
Anguilla:  85157.73333333331 ns
Speedup:  1.2159518102094462

-- FRONT SIZE (200) --
HYPERVOLUME CALCULATION
Shark bindings:  204425.34366666657 ns
Anguilla:  133510.14399999997 ns
Speedup:  1.5311596373281315
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  204554.43333333323 ns
Anguilla:  175344.5333333333 ns
Speedup:  1.1665857466139042

-- FRONT SIZE (300) --
HYPERVOLUME CALCULATION
Shark bindings:  245202.47766666647 ns
Anguilla:  162366.77866666662 ns
Speedup:  1.5101764023418773
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  337605.1 ns
Anguilla:  293921.8999999999 ns
Speedup:  1.1486217937486118

-- FRONT SIZE (400) --
HYPERVOLUME CALCULATION
Shark bindings:  319149.18433333334 ns
Anguilla:  223124.41900000002 ns
Speedup:  1.4303642145655662
HYPERVOLUME CONTRIBUTIONS
Shark bindings:  417851

## 2-D case

In [16]:
# Front with dominated points
front_0 = np.array([
    [0.16, 0.86],
    [0.66, 0.37],
    [0.79, 0.79],
    [0.28, 0.99],
    [0.51, 0.37],
    [0.92, 0.62],
    [0.16, 0.53],
    [0.01, 0.98],
    [0.67, 0.17],
    [0.79, 0.72]
])

ref_p_0 = np.array([1., 1.])

In [17]:
hv.shark_calculate(front_0, ref_p_0)

0.5421999999999999

In [18]:
hv.shark_contributions(front_0, ref_p_0)

array([-0.0396,  0.    , -0.0091, -0.0299,  0.093 ,  0.0136,  0.    ,
        0.003 ,  0.024 , -0.    ])

In [19]:
hv.calculate(front_0, ref_p_0)

0.5422

In [20]:
hv.contributions(front_0, ref_p_0)

array([0.    , 0.    , 0.    , 0.    , 0.0992, 0.    , 0.1575, 0.003 ,
       0.066 , 0.    ])

In [21]:
hv.contributions_naive(front_0, ref_p_0)

array([0.00000000e+00, 1.11022302e-16, 1.11022302e-16, 1.11022302e-16,
       2.40000000e-02, 1.11022302e-16, 1.15500000e-01, 3.00000000e-03,
       6.60000000e-02, 1.11022302e-16])

In [22]:
# Test case
front_2 = np.array([[0.0024631887,0.9503694783],
                    [1.0000000000,0.0000000000]])

front_2 = np.array([
    [0.0000004413,0.9993357234],
    [0.0132868566,0.8847313720],
    [0.0397074233,0.8007327842],
    [0.0731837522,0.7294750434],
    [0.1117377343,0.6657280534],
    [0.1543553951,0.6071191082],
    [0.2004080498,0.5523304234],
    [0.2494624831,0.5005378062],
    [0.3011993915,0.4511836450],
    [0.3553721099,0.4038690497],
    [0.4117834993,0.3582964085],
    [0.4702717382,0.3142363831],
    [0.5307012214,0.2715075694],
    [0.5929564562,0.2299633410],
    [0.6569376105,0.1894831214],
    [0.7225573788,0.1499662484],
    [0.7897387115,0.1113275567],
    [0.8584129887,0.0734942047],
    [0.9285186283,0.0364032854],
    [1.0000000000,0.0000000000]
])

ref_p_2 = np.array([11., 11.])

In [23]:
hv.calculate(front_2, ref_p_2)

120.64239629678224

In [24]:
hv.contributions(front_2, ref_p_2)

array([0.13287298, 0.00302791, 0.00281196, 0.00274727, 0.00271675,
       0.0026991 , 0.00268763, 0.00267959, 0.00267365, 0.00266908,
       0.00266546, 0.00266252, 0.00266009, 0.00265805, 0.0026563 ,
       0.0026548 , 0.00265348, 0.00265233, 0.00265131, 0.36403285])

In [25]:
hv.shark_calculate(front_2, ref_p_2)

120.64239629678224

In [26]:
hv.shark_contributions(front_2, ref_p_2)

array([0.13287298, 0.00302791, 0.00281196, 0.00274727, 0.00271675,
       0.0026991 , 0.00268763, 0.00267959, 0.00267365, 0.00266908,
       0.00266546, 0.00266252, 0.00266009, 0.00265805, 0.0026563 ,
       0.0026548 , 0.00265348, 0.00265233, 0.00265131, 0.36403285])

## Check handling of duplicates

In [27]:
front_1 = np.array([
    [0.34809801, 0.04027377, 0.95910607],
    [0.46405603, 1.18309998, 0.18992489],
    [0.32362821, 1.10760308, 0.68271139],
    [0.05260465, 0.23849614, 0.99947899],
    [0.02506317, 0.05318015, 1.13008007],
    [0.50609626, 0.59867043, 0.95899003],
    [0.76977749, 0.00581139, 1.03351874],
    [0.34809801, 0.04027377, 0.95910607],
    [0.46405603, 1.18309998, 0.18992489],
    [0.32362821, 1.10760308, 0.68271139],
    [0.05260465, 0.23849614, 0.99947899],
    [0.02506317, 0.05318015, 1.13008007],
    [0.50609626, 0.59867043, 0.95899003],
    [0.76977749, 0.00581139, 1.03351874],
])

ref_p_1 = np.array([1.2, 1.2, 1.2])

print(' '.join([str(xi) for xi in ref_p_1]))

print('')

for x in front_1:
    print(' '.join([str(xi) for xi in x]))

1.2 1.2 1.2

0.34809801 0.04027377 0.95910607
0.46405603 1.18309998 0.18992489
0.32362821 1.10760308 0.68271139
0.05260465 0.23849614 0.99947899
0.02506317 0.05318015 1.13008007
0.50609626 0.59867043 0.95899003
0.76977749 0.00581139 1.03351874
0.34809801 0.04027377 0.95910607
0.46405603 1.18309998 0.18992489
0.32362821 1.10760308 0.68271139
0.05260465 0.23849614 0.99947899
0.02506317 0.05318015 1.13008007
0.50609626 0.59867043 0.95899003
0.76977749 0.00581139 1.03351874


In [28]:
hv.contributions(front_1, ref_p_1)

array([3.66516637e-02, 6.12901623e-03, 1.90283493e-02, 3.68108380e-02,
       6.03721961e-03, 4.09795572e-05, 2.46833301e-03, 3.66516637e-02,
       6.12901623e-03, 1.90283493e-02, 3.68108380e-02, 6.03721961e-03,
       4.09795572e-05, 2.46833301e-03])

In [29]:
hv.calculate(front_1, ref_p_1)

0.3321159750270065

In [30]:
hv.shark_contributions(front_1, ref_p_1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
hv.shark_calculate(front_1, ref_p_1)

0.3321159750270065

In [32]:
hv.contributions_naive(front_1, ref_p_1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])