In [1]:
! pip install cma

     |████████████████████████████████| 230 kB 214 kB/s eta 0:00:01


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import timeit

import numpy as np
import cma
from IPython.display import display, clear_output

from anguilla.optimizers.cma import CMA, StrategyParameters, StoppingConditions
from anguilla.fitness.benchmark import Sphere, SumSquares

In [4]:
def test_with_pycma(n=4):
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    initial_sigma = 0.3
    cma.fmin(fitness_function, initial_point, initial_sigma, options={'CMA_Active': 0})

test_with_pycma()

(4_w,8)-CMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=922544, Tue Dec  1 14:41:17 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      8 2.650231767300454e+00 1.0e+00 3.18e-01  3e-01  4e-01 0:00.0
    2     16 2.011003680851720e+00 1.3e+00 3.54e-01  3e-01  4e-01 0:00.0
    3     24 1.421651846753808e+00 1.4e+00 3.57e-01  3e-01  4e-01 0:00.0
  100    800 1.755719619789397e-12 1.6e+00 2.47e-05  7e-07  9e-07 0:00.3
  114    912 1.541075555804607e-14 1.3e+00 5.65e-06  1e-07  1e-07 0:00.3
termination on tolfun=1e-11 (Tue Dec  1 14:41:21 2020)
final/bestever f-value = 4.586217e-15 4.586217e-15
incumbent solution: [2.299713954011094e-08, -8.504234102919866e-09, -1.1290893213914133e-08, 6.21091130009141e-08]
std deviation: [1.0449667141321544e-07, 1.1329506118539404e-07, 1.1141398945644381e-07, 1.0260906509996936e-07]


In [7]:
def test_with_prototype(n=4):
    parameters = StrategyParameters(n=n)
    conditions = StoppingConditions(n=n,
                                    population_size=parameters.population_size,
                                    ftarget=1e-14,
                                    )
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    optimizer = CMA(initial_point=initial_point,
                    initial_sigma=0.3,
                    strategy_parameters=parameters,
                    stopping_conditions=conditions)
    while not optimizer.stop():
        candidate_solutions = optimizer.ask()
        function_values = fitness_function(candidate_solutions.T)
        function_evaluations = fitness_function.eval_count
        ranked_indices = optimizer.rank(candidate_solutions, function_values, function_evaluations)
        optimizer.tell(candidate_solutions, ranked_indices)
        if (optimizer._fevals % 20) == 0:
            display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)
    display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)

test_with_prototype(n=4)

20

0.6529910208337285

array([ 0.4787809 ,  0.51181387, -0.35753674,  0.18432015])

40

0.15357226629061202

array([ 0.06473068,  0.36336145,  0.13040122, -0.01860594])

60

0.08541015300765986

array([ 0.20808282, -0.01208508,  0.00476628,  0.20479972])

80

0.08541015300765986

array([ 0.20808282, -0.01208508,  0.00476628,  0.20479972])

100

0.01644883361773452

array([ 0.04627849,  0.08893885, -0.01581036, -0.07840311])

120

0.0012414573099067173

array([0.00847652, 0.02460342, 0.02163831, 0.0098011 ])

140

0.0012414573099067173

array([0.00847652, 0.02460342, 0.02163831, 0.0098011 ])

160

0.0011480991788651823

array([ 0.00423   , -0.01096124,  0.03112763, -0.00641311])

180

0.0010288932068796119

array([ 0.01868767, -0.00443669, -0.01378262,  0.02167993])

200

0.00047980015351893493

array([0.00971327, 0.00786845, 0.00403421, 0.01752898])

220

0.00011252352610621025

array([-0.00168791,  0.00370193,  0.00952411,  0.00229379])

240

1.822750221002208e-05

array([ 0.00185274,  0.0032808 , -0.00199071,  0.00026133])

260

1.822750221002208e-05

array([ 0.00185274,  0.0032808 , -0.00199071,  0.00026133])

280

4.242838074868671e-06

array([-1.60014444e-03,  2.46468903e-05, -3.28192772e-04, -1.25461463e-03])

300

4.242838074868671e-06

array([-1.60014444e-03,  2.46468903e-05, -3.28192772e-04, -1.25461463e-03])

320

3.3308597458018604e-06

array([-0.00106867,  0.00065002, -0.00123167, -0.00049928])

340

3.3308597458018604e-06

array([-0.00106867,  0.00065002, -0.00123167, -0.00049928])

360

1.5201891383976308e-06

array([ 3.34042769e-05, -7.10627526e-04,  9.93784364e-04,  1.62709710e-04])

380

1.928084677213214e-07

array([-1.83399298e-04, -1.13811516e-04,  3.73836785e-04,  8.04124490e-05])

400

1.1806454004205896e-07

array([-5.16736557e-05, -5.75234051e-05,  2.55683531e-04,  2.16128117e-04])

420

1.1806454004205896e-07

array([-5.16736557e-05, -5.75234051e-05,  2.55683531e-04,  2.16128117e-04])

440

9.429904674086594e-08

array([ 8.55842298e-05, -2.25291983e-04, -8.90352404e-05,  1.68198201e-04])

460

3.470179521497815e-08

array([-2.38965424e-05, -1.69370341e-04, -5.51573272e-05,  4.90112979e-05])

480

1.4003436399789878e-08

array([ 3.16348909e-06,  3.59245020e-05, -4.10593754e-05, -1.04961834e-04])

500

5.062127667889443e-09

array([ 6.22791367e-05,  1.12040722e-05,  3.23121439e-05, -3.71899429e-06])

520

3.181487049023334e-09

array([ 2.93426681e-06,  4.25772680e-05,  3.53124407e-05, -1.06341388e-05])

540

1.454021221113048e-09

array([-2.04487951e-05,  1.23874484e-05, -2.02690710e-05, -2.17159823e-05])

560

9.990610200556364e-11

array([5.84110810e-06, 3.57541660e-06, 5.49124038e-06, 4.78019177e-06])

580

9.990610200556364e-11

array([5.84110810e-06, 3.57541660e-06, 5.49124038e-06, 4.78019177e-06])

600

9.990610200556364e-11

array([5.84110810e-06, 3.57541660e-06, 5.49124038e-06, 4.78019177e-06])

620

9.706488330207251e-11

array([ 7.36842921e-06,  8.88395088e-07, -3.66836324e-06,  5.34088004e-06])

640

7.351192747538429e-11

array([ 3.22499998e-06, -2.29154523e-06,  3.17906395e-06,  6.91040342e-06])

660

1.4802792745973832e-11

array([ 4.95941335e-07, -2.41344472e-06,  9.52355349e-07,  2.79734495e-06])

680

7.432590555412575e-12

array([-3.51618764e-08, -8.10444111e-07, -2.58714288e-06, -2.85002217e-07])

700

3.1233205298129088e-12

array([-8.58766484e-07, -9.96213688e-07, -2.85880558e-07, -1.14528217e-06])

720

4.4022727129862503e-13

array([-4.07746167e-07, -3.86582269e-07,  7.60091802e-08,  3.44596994e-07])

740

1.0294188677196537e-13

array([1.07968766e-08, 2.46010213e-07, 4.35961768e-08, 2.01006624e-07])

760

1.0294188677196537e-13

array([1.07968766e-08, 2.46010213e-07, 4.35961768e-08, 2.01006624e-07])

780

8.461482252110534e-14

array([ 2.25920040e-07,  1.25741567e-08, -1.04494663e-07, -1.49992379e-07])

800

2.317533925195287e-14

array([ 5.88258833e-08, -7.93363841e-08,  2.74197506e-09, -1.15814828e-07])

820

3.631980714436554e-15

array([-4.81402844e-08,  1.46505121e-08, -3.03936228e-08,  1.32696614e-08])

820

3.631980714436554e-15

array([-4.81402844e-08,  1.46505121e-08, -3.03936228e-08,  1.32696614e-08])