In [1]:
! pip install cma

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import timeit

import numpy as np
import cma
from IPython.display import display, clear_output

from anguilla.optimizers.cma import CMA, StrategyParameters, StoppingConditions
from anguilla.fitness.benchmark import Sphere, SumSquares

In [4]:
def test_with_pycma(n=4):
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    initial_sigma = 0.3
    cma.fmin(fitness_function, initial_point, initial_sigma, options={'CMA_Active': 0})

test_with_pycma()

(4_w,8)-CMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=556575, Thu Nov 26 12:19:19 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      8 3.077208987461802e+00 1.0e+00 2.87e-01  3e-01  3e-01 0:00.0
    2     16 1.972025418004691e+00 1.2e+00 2.87e-01  3e-01  3e-01 0:00.0
    3     24 8.563327312513337e-01 1.2e+00 3.54e-01  3e-01  4e-01 0:00.0
  100    800 8.904745969751205e-15 1.5e+00 2.91e-06  6e-08  8e-08 0:00.3
  107    856 1.517587209868988e-15 1.4e+00 1.43e-06  2e-08  3e-08 0:00.3
termination on tolfun=1e-11 (Thu Nov 26 12:19:24 2020)
final/bestever f-value = 7.400358e-16 3.733785e-16
incumbent solution: [-1.221413785898568e-08, 1.6757729576581114e-08, 8.571142920895e-09, -1.5380656831008103e-08]
std deviation: [2.573309680349744e-08, 2.823659464002505e-08, 2.3413816352184244e-08, 2.2437228132830215e-08]


In [5]:
def test_with_prototype(n=4):
    parameters = StrategyParameters(n=n)
    conditions = StoppingConditions(n=n,
                                    population_size=parameters.population_size,
                                    ftarget=1e-14,
                                    )
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    optimizer = CMA(initial_point=initial_point,
                    initial_sigma=0.3,
                    strategy_parameters=parameters,
                    stopping_conditions=conditions)
    while not optimizer.stop():
        candidate_solutions = optimizer.ask()
        function_values = fitness_function(candidate_solutions.T)
        ranked_indices = optimizer.rank(candidate_solutions, function_values)
        optimizer.tell(candidate_solutions, ranked_indices)
        if (optimizer._fevals % 20) == 0:
            display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)

test_with_prototype(n=4)

20

0.13964790258374316

array([-0.03554292, -0.18841616, -0.28480109, -0.14755438])

40

0.13964790258374316

array([-0.03554292, -0.18841616, -0.28480109, -0.14755438])

60

0.012709183810259053

array([ 0.02884791, -0.10196224,  0.01108867, -0.03684732])

80

0.012709183810259053

array([ 0.02884791, -0.10196224,  0.01108867, -0.03684732])

100

0.005549328122215536

array([ 0.002783  , -0.06219967,  0.02487529,  0.03246544])

120

0.0010410904845685079

array([ 0.00249361, -0.00824022,  0.02823926, -0.01301981])

140

0.0007711993517598604

array([-0.01749174, -0.01447167,  0.01139781,  0.01122048])

160

0.00018035555046556616

array([-0.00903535, -0.00318042,  0.00704597,  0.00624158])

180

0.00018035555046556616

array([-0.00903535, -0.00318042,  0.00704597,  0.00624158])

200

2.031624156882762e-05

array([ 0.0037639 ,  0.00173428, -0.00016669,  0.00176459])

220

2.031624156882762e-05

array([ 0.0037639 ,  0.00173428, -0.00016669,  0.00176459])

240

1.0570058048614711e-05

array([-0.00111063,  0.00250357,  0.00012824, -0.00174707])

260

2.783875993694177e-06

array([-0.00047155,  0.00104746, -0.00105065, -0.00060039])

280

3.8986277842707337e-07

array([5.08789696e-04, 8.90177621e-05, 3.37719410e-04, 9.49592653e-05])

300

1.7113547599377943e-07

array([-2.85429459e-04, -2.97350488e-04, -3.51691378e-05,  3.36436724e-06])

320

1.7113547599377943e-07

array([-2.85429459e-04, -2.97350488e-04, -3.51691378e-05,  3.36436724e-06])

340

5.538284142912483e-08

array([-1.56906473e-04,  4.40293657e-05,  1.02485529e-04,  1.35356312e-04])

360

3.268852179894142e-08

array([-1.09891944e-04,  1.41108686e-04,  7.68528877e-06,  2.53289891e-05])

380

7.999901041925891e-09

array([ 7.97378966e-06,  1.44159860e-05,  4.75314175e-05, -7.39544686e-05])

400

4.185959038085839e-09

array([-2.87317298e-06, -5.31929288e-05, -7.27849393e-06, -3.59894396e-05])

420

6.018538718313959e-10

array([-2.14556650e-05, -6.81597280e-06, -6.89088173e-06, -6.89685239e-06])

440

3.59646302106873e-10

array([ 2.04119109e-06, -1.84281968e-05,  1.08440670e-06,  3.83477046e-06])

460

2.8396181742484594e-10

array([-9.20353511e-06,  6.52958316e-06, -1.17329489e-05, -4.35421769e-06])

480

5.7448839345497116e-11

array([-3.58840256e-06,  5.38446515e-06, -3.94571124e-06, -1.05376911e-07])

500

5.116293619469079e-11

array([-4.75388976e-06, -5.22482880e-06,  1.03573617e-06,  4.38044363e-07])

520

9.95565844321961e-12

array([ 1.59905576e-06,  2.66118725e-06, -1.74167608e-07,  5.35188940e-07])

540

4.153401405890945e-12

array([ 9.36555368e-07,  4.71302525e-07,  1.39251292e-06, -1.05595792e-06])

560

1.3108784555548049e-12

array([-7.64745774e-07, -3.55032212e-07,  7.36280976e-07, -2.40592620e-07])

580

7.150456120083642e-13

array([-7.56654783e-07, -3.07233551e-07,  1.56705012e-08,  2.18817577e-07])

600

1.1024684279629375e-13

array([-2.42787811e-07,  2.33061657e-08,  5.52728176e-08,  2.18409387e-07])

620

1.1024684279629375e-13

array([-2.42787811e-07,  2.33061657e-08,  5.52728176e-08,  2.18409387e-07])

640

1.1024684279629375e-13

array([-2.42787811e-07,  2.33061657e-08,  5.52728176e-08,  2.18409387e-07])

660

4.047552640003401e-14

array([ 4.60829023e-10, -9.23439167e-08, -1.65572801e-07,  6.73317358e-08])

680

1.2490559918109497e-14

array([-5.69125997e-08,  1.85515115e-08, -5.01520277e-08, -7.99508064e-08])

700

6.898520830577873e-15

array([ 1.71231329e-08,  1.79222549e-08, -7.26058950e-08,  3.18197414e-08])