In [1]:
! pip install cma

     |████████████████████████████████| 230 kB 155 kB/s eta 0:00:01


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import timeit

import numpy as np
import cma
from IPython.display import display, clear_output

from anguilla.optimizers.cma import CMA, StrategyParameters, StoppingConditions
from anguilla.fitness.benchmark import Sphere, SumSquares

In [7]:
def test_with_pycma(n=4):
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    initial_sigma = 0.3
    cma.fmin(fitness_function, initial_point, initial_sigma, options={'CMA_Active': 0})

test_with_pycma()

(4_w,8)-CMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=720738, Sun Nov 29 00:27:55 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      8 7.790223198024215e-01 1.0e+00 2.83e-01  3e-01  3e-01 0:00.0
    2     16 3.845624480190633e-01 1.1e+00 2.91e-01  3e-01  3e-01 0:00.0
    3     24 2.784872783050687e-01 1.2e+00 3.15e-01  3e-01  3e-01 0:00.0
  100    800 1.035019245906245e-13 1.6e+00 1.08e-05  3e-07  4e-07 0:00.3
  112    896 3.267393054913799e-15 1.4e+00 1.31e-06  2e-08  2e-08 0:00.3
termination on tolfun=1e-11 (Sun Nov 29 00:27:59 2020)
final/bestever f-value = 3.100885e-15 2.113454e-15
incumbent solution: [5.123875486645053e-09, -5.2446199674011465e-08, 3.434494610055259e-10, -1.799748709826705e-08]
std deviation: [2.1148474246063247e-08, 2.150244810065341e-08, 2.059083318946686e-08, 1.869662470600328e-08]


In [9]:
def test_with_prototype(n=4):
    parameters = StrategyParameters(n=n)
    conditions = StoppingConditions(n=n,
                                    population_size=parameters.population_size,
                                    ftarget=1e-14,
                                    )
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    optimizer = CMA(initial_point=initial_point,
                    initial_sigma=0.3,
                    strategy_parameters=parameters,
                    stopping_conditions=conditions)
    while not optimizer.stop():
        candidate_solutions = optimizer.ask()
        function_values = fitness_function(candidate_solutions.T)
        ranked_indices = optimizer.rank(candidate_solutions, function_values)
        optimizer.tell(candidate_solutions, ranked_indices)
        if (optimizer._fevals % 20) == 0:
            display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)
    display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)

test_with_prototype(n=4)

20

6.985819637441909

array([ 0.45917604, -0.14509201,  0.56417126, -2.53685555])

40

3.41088752353529

array([ 0.30335675,  0.05392284, -0.331734  , -1.7905047 ])

60

1.1065744694036743

array([-0.16931239,  0.51822083, -0.41431716, -0.79855885])

80

0.544200545403552

array([ 0.2198265 ,  0.25575262, -0.46983403, -0.45795571])

100

0.16829034936166748

array([ 0.04198509,  0.26666445, -0.21666109, -0.22017185])

120

0.06824640721575646

array([-0.10627042,  0.13362846,  0.03790335, -0.19406127])

140

0.017225325475907313

array([0.03417428, 0.04304885, 0.11393832, 0.03496141])

160

0.015116611595772081

array([-0.00531119,  0.11089075, -0.05057752,  0.01528262])

180

0.004798384398305573

array([ 0.00872046, -0.03592966,  0.00120998,  0.05856563])

200

0.0029964538617444046

array([ 0.03370265,  0.0213256 , -0.02611668, -0.0269021 ])

220

0.0013881445294006245

array([ 0.0323044 , -0.01833672,  0.00276323,  0.00083651])

240

0.00035251163206362855

array([ 0.00665633, -0.00905107, -0.01372222,  0.0061631 ])

260

0.00035251163206362855

array([ 0.00665633, -0.00905107, -0.01372222,  0.0061631 ])

280

0.00023761434873844468

array([-0.00867588, -0.00225893, -0.00971771,  0.00792507])

300

0.00015798189715673293

array([ 0.00284535,  0.00198555, -0.01105352, -0.00487476])

320

2.6966800114654973e-05

array([-1.23527594e-05,  4.68714823e-03, -1.19471278e-03, -1.88943123e-03])

340

1.9347277221822385e-05

array([-0.00239505,  0.00225451, -0.00035254,  0.00289895])

360

6.794784634572881e-06

array([-0.00195892, -0.00063136,  0.00152339, -0.00048795])

380

4.85049337305331e-06

array([-5.76973542e-05, -3.87385825e-04,  1.86496044e-03,  1.10409201e-03])

400

9.92333725429198e-07

array([-6.62203079e-05,  8.26403274e-04,  3.76212453e-04, -4.04314747e-04])

420

1.3417377350366571e-07

array([ 2.14578110e-04,  7.18683149e-05, -1.39577735e-04, -2.51958348e-04])

440

1.3417377350366571e-07

array([ 2.14578110e-04,  7.18683149e-05, -1.39577735e-04, -2.51958348e-04])

460

4.381048415510233e-08

array([ 6.94815833e-05,  1.65353096e-04,  4.32865666e-05, -9.88302606e-05])

480

4.137693436154747e-08

array([-9.17966793e-05,  1.18793615e-04, -1.04881918e-04, -8.85334090e-05])

500

1.4033457925730318e-08

array([ 3.60763049e-06,  7.43203709e-05,  3.26866774e-05, -8.61887842e-05])

520

1.2964980543234814e-09

array([ 2.60017091e-05,  2.31106828e-05,  9.27870542e-06, -4.59502279e-07])

540

1.2964980543234814e-09

array([ 2.60017091e-05,  2.31106828e-05,  9.27870542e-06, -4.59502279e-07])

560

6.646002249630034e-10

array([2.34528824e-06, 1.82626514e-05, 9.91420021e-06, 1.50759427e-05])

580

6.176010473700785e-10

array([ 1.31757824e-05,  2.04402009e-05,  4.97352247e-06, -1.20915895e-06])

600

3.266583622779734e-10

array([-6.69938314e-06,  1.38559788e-05, -2.73025008e-06, -9.07382026e-06])

620

1.9000169558231607e-10

array([3.39760743e-07, 4.33141195e-06, 1.30789126e-05, 2.59179433e-07])

640

1.0071066666288537e-10

array([ 3.73425332e-06,  7.89395216e-06,  4.48113263e-06, -2.09069090e-06])

660

9.479043798838e-12

array([-6.67269924e-07,  5.60543951e-08,  1.32245672e-07, -3.00219314e-06])

680

3.5462249352002107e-12

array([-1.28865250e-06, -4.78336836e-07, -8.11942304e-07,  9.98770864e-07])

700

3.5462249352002107e-12

array([-1.28865250e-06, -4.78336836e-07, -8.11942304e-07,  9.98770864e-07])

720

3.5462249352002107e-12

array([-1.28865250e-06, -4.78336836e-07, -8.11942304e-07,  9.98770864e-07])

740

1.471319326865501e-12

array([-5.45590406e-07,  9.99220864e-07, -3.99567584e-07,  1.24715058e-07])

760

8.79324853970148e-13

array([ 4.07882870e-07, -7.00286288e-07, -3.58697611e-07, -3.06417292e-07])

780

4.009903814860918e-13

array([ 3.73906935e-07,  3.27531313e-07, -4.38076768e-08,  3.89856527e-07])

800

1.567298606122546e-13

array([-4.95722970e-08,  1.95380507e-07,  1.93140440e-07, -2.80705675e-07])

820

1.0750627733300408e-13

array([-3.12094528e-07, -5.15126397e-08,  1.86051086e-08,  8.42827443e-08])

840

3.1985533470160406e-14

array([-1.23101027e-07, -3.94755193e-08,  7.24712616e-08, -1.00106295e-07])

845

2.2673874667687895e-15

array([-2.29839331e-08,  3.44687446e-08,  2.31646493e-08,  3.79880982e-09])