In [1]:
! pip install cma

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import timeit

import numpy as np
import cma
from IPython.display import display, clear_output

from anguilla.optimizers.cma import CMA, StrategyParameters, StoppingConditions
from anguilla.fitness.benchmark import Sphere, SumSquares

In [4]:
def test_with_pycma(n=4, d=3):
    fitness_function = Sphere(d)
    initial_point = fitness_function.random_points(1)
    initial_sigma = 0.3
    cma.fmin(fitness_function, initial_point, initial_sigma, options={'CMA_Active': 0})

test_with_pycma()

(3_w,7)-CMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=84634, Thu Dec  3 17:05:57 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      7 1.830289009606220e-01 1.0e+00 3.00e-01  3e-01  3e-01 0:00.0
    2     14 5.129514262188250e-02 1.2e+00 3.36e-01  3e-01  4e-01 0:00.0
    3     21 3.717807645583373e-01 1.4e+00 3.37e-01  3e-01  4e-01 0:00.0
   96    672 5.823227703555781e-15 1.6e+00 9.70e-06  7e-08  1e-07 0:00.3
termination on tolfun=1e-11 (Thu Dec  3 17:06:01 2020)
final/bestever f-value = 3.069588e-15 3.069588e-15
incumbent solution: [8.463640111882815e-09, -9.212800156691295e-09, -5.397294361878817e-08]
std deviation: [1.044696143369427e-07, 7.080393757770522e-08, 7.965942174222113e-08]


In [5]:
def test_with_prototype(n=4,d=3):
    parameters = StrategyParameters(n=n)
    conditions = StoppingConditions(n=n,
                                    population_size=parameters.population_size,
                                    ftarget=1e-14,
                                    )
    fitness_function = Sphere(d)
    initial_point = fitness_function.random_points(1)
    optimizer = CMA(initial_point=initial_point,
                    initial_sigma=0.3,
                    strategy_parameters=parameters,
                    stopping_conditions=conditions)
    while not optimizer.stop():
        candidate_solutions = optimizer.ask()
        function_values = fitness_function(candidate_solutions.T)
        function_evaluations = fitness_function.evaluation_count
        ranked_indices = optimizer.rank(candidate_solutions, function_values, function_evaluations)
        optimizer.tell(candidate_solutions, ranked_indices)
        if (optimizer._fevals % 20) == 0:
            display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)
    display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)

test_with_prototype(n=4)

20

1.2632946512518723

array([-0.0034661 , -0.99632687, -0.52020707])

40

0.10572180857134589

array([ 0.14957923, -0.19598826,  0.21198223])

60

0.060386975079054946

array([ 0.2254929 , -0.05482095, -0.08083682])

80

0.056485906498924134

array([ 0.1446555 ,  0.16681643, -0.08793732])

100

0.009121292283500872

array([-0.0461883 , -0.04317725, -0.07157973])

120

0.0011832198046677267

array([0.00093362, 0.00300674, 0.03425358])

140

0.001166123756894465

array([-0.03269084, -0.00260417, -0.00952107])

160

0.00017332317876524444

array([0.01128294, 0.00090536, 0.006723  ])

180

4.741984626030977e-05

array([ 0.0025458 , -0.00588979,  0.00249982])

200

1.541044957772006e-05

array([-0.00104579,  0.00257815,  0.00276946])

220

1.3522994255611932e-05

array([ 0.00280961, -0.00085476,  0.00221325])

240

3.0138676991204196e-06

array([-0.00151399,  0.00034595, -0.0007759 ])

260

1.4935975885860178e-07

array([ 5.54042719e-05,  1.99063615e-04, -3.26594248e-04])

280

1.4935975885860178e-07

array([ 5.54042719e-05,  1.99063615e-04, -3.26594248e-04])

300

1.4935975885860178e-07

array([ 5.54042719e-05,  1.99063615e-04, -3.26594248e-04])

320

7.283064118449695e-08

array([0.00017369, 0.00012093, 0.00016745])

340

9.333074606738915e-09

array([ 5.94932154e-05, -7.35188761e-05,  1.97131119e-05])

360

9.333074606738915e-09

array([ 5.94932154e-05, -7.35188761e-05,  1.97131119e-05])

380

8.205188858450371e-10

array([-1.45039631e-05, -2.46260355e-05, -1.92673678e-06])

400

8.205188858450371e-10

array([-1.45039631e-05, -2.46260355e-05, -1.92673678e-06])

420

2.0919997318893856e-10

array([1.04233036e-05, 1.27358042e-06, 9.94649230e-06])

440

1.5984115443762646e-10

array([ 4.37562791e-06,  1.11550107e-05, -4.03246470e-06])

460

5.659256217796467e-11

array([ 4.65139662e-06,  4.53870034e-06, -3.78909896e-06])

480

2.4745050607351595e-11

array([-4.82550394e-06, -9.53478679e-07, -7.41916967e-07])

500

1.824147141124375e-12

array([-1.12649117e-06,  7.28738256e-07,  1.55258946e-07])

520

1.7278558365946818e-12

array([ 6.66923179e-08,  6.78076231e-09, -1.31276883e-06])

540

1.0422632636493789e-12

array([-4.30909170e-07, -8.63650784e-07, -3.32697873e-07])

560

1.860002343695178e-13

array([ 3.66121656e-07, -8.71008154e-08,  2.10638590e-07])

580

1.9201146404427635e-14

array([ 1.08125562e-07,  8.27037959e-08, -2.58861234e-08])

600

1.1333508882191525e-14

array([-6.54382514e-08, -1.66907459e-08, -8.22967991e-08])

610

1.468215888239096e-15

array([-1.43990795e-08,  3.51280064e-08, -5.18705754e-09])