In [1]:
! pip install cma

     |████████████████████████████████| 230 kB 699 kB/s eta 0:00:01


In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import timeit

import numpy as np
import cma
from IPython.display import display, clear_output

from anguilla.optimizers.cma import CMA, StrategyParameters, StoppingConditions
from anguilla.fitness.benchmark import Sphere, SumSquares

In [3]:
def test_with_pycma(n=4):
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    initial_sigma = 0.3
    cma.fmin(fitness_function, initial_point, initial_sigma, options={'CMA_Active': 0})

test_with_pycma()

(4_w,8)-CMA-ES (mu_w=2.6,w_1=52%) in dimension 4 (seed=475004, Thu Nov 26 04:10:53 2020)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      8 4.092089506002811e+00 1.0e+00 3.55e-01  3e-01  4e-01 0:00.0
    2     16 2.474184999512569e+00 1.1e+00 4.74e-01  5e-01  5e-01 0:00.0
    3     24 1.451724118995040e+00 1.2e+00 6.46e-01  6e-01  7e-01 0:00.0
  100    800 1.035602852733542e-13 1.5e+00 1.30e-05  3e-07  4e-07 0:00.4
  113    904 4.546229930830256e-15 1.6e+00 4.27e-06  6e-08  9e-08 0:00.5
termination on tolfun=1e-11 (Thu Nov 26 04:10:58 2020)
final/bestever f-value = 2.895012e-15 2.895012e-15
incumbent solution: [1.9294181211161087e-08, -7.933897761477204e-09, -4.738194833547888e-08, 1.4654381448775531e-08]
std deviation: [8.141071626222936e-08, 7.048185732234207e-08, 6.347768198276708e-08, 8.797508817776637e-08]


In [4]:
def test_with_prototype(n=4):
    parameters = StrategyParameters(n=n)
    conditions = StoppingConditions(n=n,
                                    population_size=parameters.population_size,
                                    ftarget=1e-14,
                                    )
    fitness_function = Sphere()
    initial_point = fitness_function.propose_initial_point(n)
    optimizer = CMA(initial_point=initial_point,
                    initial_sigma=0.3,
                    strategy_parameters=parameters,
                    stopping_conditions=conditions)
    while not optimizer.stop():
        candidate_solutions = optimizer.ask()
        function_values = fitness_function(candidate_solutions.T)
        ranked_indices = optimizer.rank(candidate_solutions, function_values)
        optimizer.tell(candidate_solutions, ranked_indices)
        if (optimizer._fevals % 20) == 0:
            display(optimizer._fevals, optimizer._best_value, optimizer._best_solution)

In [5]:
test_with_prototype(n=4)

20

4.189925594216071

array([-1.88365048,  0.00288588, -0.73233761,  0.3247457 ])

40

0.480606102934387

array([-0.16263138, -0.49408241,  0.11280156, -0.44420211])

60

0.25591360500768984

array([ 0.11549737, -0.46864701, -0.00793108, -0.15126482])

80

0.07467246057911296

array([ 0.06237988, -0.19290104,  0.13952597, -0.11875565])

100

0.03429983208957598

array([-0.0755654 , -0.02032804, -0.16596951, -0.02511167])

120

0.03429983208957598

array([-0.0755654 , -0.02032804, -0.16596951, -0.02511167])

140

0.008370075702558273

array([-0.02009519, -0.03705606, -0.06353668, -0.05055885])

160

0.005397635165981025

array([ 0.0284865 , -0.0620872 , -0.02147801, -0.01643256])

180

0.0026476062132154716

array([ 0.00492027,  0.03091048, -0.02747387, -0.03021798])

200

0.0023642117038678934

array([-0.00647109,  0.02931067, -0.0178586 ,  0.03382738])

220

0.0014698937189558552

array([ 0.00182665, -0.00521914, -0.03202428,  0.02034117])

240

0.001070813036938993

array([ 0.00756906, -0.01139464, -0.02935208, -0.00470533])

260

0.0004623798315535843

array([ 0.00694603,  0.00690625, -0.0187936 , -0.00363825])

280

0.00016651275836138083

array([-0.00198276,  0.00492022, -0.01116573,  0.00370127])

300

0.00010380694132241389

array([-0.0002646 ,  0.00391655, -0.00938351, -0.00058935])

320

3.228553107237257e-05

array([ 0.0003565 , -0.00257725, -0.0049222 ,  0.00113499])

340

1.6301012433513297e-05

array([ 0.00361629,  0.00063474, -0.00063518,  0.0015547 ])

360

7.265483722633531e-06

array([ 0.00122328,  0.00235054, -0.00045721,  0.00018705])

380

2.9432825305328666e-07

array([ 4.72034966e-04,  1.67625297e-04, -2.06247783e-04, -2.95779672e-05])

400

2.9432825305328666e-07

array([ 4.72034966e-04,  1.67625297e-04, -2.06247783e-04, -2.95779672e-05])

420

2.9432825305328666e-07

array([ 4.72034966e-04,  1.67625297e-04, -2.06247783e-04, -2.95779672e-05])

440

3.969359758383194e-08

array([-5.07019534e-05,  1.06723002e-04, -6.28774440e-05,  1.47578919e-04])

460

3.969359758383194e-08

array([-5.07019534e-05,  1.06723002e-04, -6.28774440e-05,  1.47578919e-04])

480

1.6082721615063806e-08

array([9.91849274e-05, 6.65816797e-05, 4.22041879e-05, 5.54601220e-06])

500

6.151442683361152e-09

array([ 8.47956926e-06, -3.68575533e-06,  1.20195840e-05,  7.69511819e-05])

520

2.0161264161168655e-09

array([-3.58991841e-05, -2.16189412e-05, -9.41761560e-06, -1.30883495e-05])

540

1.8856032404450945e-09

array([ 1.08141972e-06, -3.52775563e-05, -2.43209598e-05, -6.95835500e-06])

560

3.920124189366006e-10

array([-1.67627793e-05,  9.06772848e-06,  1.22106315e-07, -5.36498263e-06])

580

3.601941782313042e-11

array([ 1.15919883e-06,  4.12796602e-06,  2.35652639e-06, -3.47596833e-06])

600

3.601941782313042e-11

array([ 1.15919883e-06,  4.12796602e-06,  2.35652639e-06, -3.47596833e-06])

620

2.9665510734509726e-11

array([-3.73461160e-07,  3.37217623e-06, -3.63589665e-06, -2.22142308e-06])

640

1.8881737128873936e-11

array([ 2.34612116e-06, -5.58955050e-07,  1.38394738e-06, -3.33911837e-06])

660

2.2254252603581768e-12

array([-9.52476327e-07,  2.07557741e-07, -9.63595422e-08, -1.12509943e-06])

680

1.6815698283299422e-12

array([-8.69105482e-08, -4.44861794e-07, -1.20745421e-06, -1.34791306e-07])

700

6.17334460279674e-13

array([-6.65413581e-07,  3.96140171e-07, -4.75389167e-08, -1.23984848e-07])

720

3.9894131514065033e-13

array([7.67062760e-09, 5.85700908e-07, 1.95979608e-07, 1.32018621e-07])

740

4.742080829208685e-14

array([-1.08658213e-08,  1.86389596e-07,  2.05263984e-08, -1.10183155e-07])

760

4.742080829208685e-14

array([-1.08658213e-08,  1.86389596e-07,  2.05263984e-08, -1.10183155e-07])

780

2.750956369628505e-14

array([ 1.09486538e-07, -1.11237871e-07, -2.55003421e-08, -4.99812997e-08])

800

6.418551269408425e-15

array([-2.18972851e-08,  8.55731258e-09,  2.73564635e-09,  7.65398511e-08])